version: '3'

services:
  prometheus-new:
    image: prom/prometheus:latest
    container_name: prometheus-new
    user: "65534:65534"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/volume_nyc3_01_monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana-new:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: grafana-new-setup
      volumes:
        - ./grafana-config:/etc/grafana
        - ./grafana-data:/var/lib/grafana	
      user: "472:472"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this to your preferred password
      ports:
        - "3000:3000"

  cadvisor-new:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-new
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"

  loki-new:
    image: grafana/loki:2.8.0
    container_name: loki-new
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - /mnt/volume_nyc3_01_monitoring/loki_data:/loki

  promtail-new:
    image: grafana/promtail:2.8.0
    container_name: promtail-new
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
